stages:
  - sast
  - tag
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH

before_script:
  - set -e

sast:
  stage: sast
include:
- template: Security/SAST.gitlab-ci.yml

Build Release:
  stage: deploy
  image: docker:stable
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  services:
    - docker:stable-dind
  script:
    - docker pull $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} || true
    - docker build --cache-from $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} --build-arg VERSION="$CI_COMMIT_REF_NAME" --tag $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} .
    - docker push $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG}

Update Version:
  image: node:16
  stage: tag
  only:
    - tags
  artifacts:
    expire_in: 1 day
    paths:
      - package-lock.json
      - package.json
  script:
    - npm --no-git-tag-version version $CI_COMMIT_TAG

Build Production:
  stage: deploy
  image: docker:stable
  only:
    - tags
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  services:
    - docker:stable-dind
  script:
    - docker pull $CONTAINER_IMAGE:stable || true
    - docker build --cache-from $CONTAINER_IMAGE:stable --build-arg VERSION="$CI_COMMIT_TAG" --tag $CONTAINER_IMAGE:${CI_COMMIT_TAG} --tag $CONTAINER_IMAGE:stable .
    - docker push $CONTAINER_IMAGE:${CI_COMMIT_TAG}
    - docker push $CONTAINER_IMAGE:stable
