stages:
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH

before_script:
  - set -e

Build Release:
  stage: deploy
  image: docker:stable
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  services:
    - docker:stable-dind
  script:
    - docker pull $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} || true
    - docker build --cache-from $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} --build-arg VERSION="$CI_COMMIT_REF_NAME" --tag $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG} .
    - docker push $CONTAINER_IMAGE:${CI_COMMIT_REF_SLUG}

Build Production:
  stage: deploy
  image: docker:stable
  only:
    - tags
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  services:
    - docker:stable-dind
  script:
    - docker pull $CONTAINER_IMAGE:stable || true
    - docker build --cache-from $CONTAINER_IMAGE:stable --build-arg VERSION="$CI_COMMIT_TAG" --tag $CONTAINER_IMAGE:${CI_COMMIT_TAG} --tag $CONTAINER_IMAGE:stable .
    - docker push $CONTAINER_IMAGE:${CI_COMMIT_TAG}
    - docker push $CONTAINER_IMAGE:stable
